
//---------------------------------------------------------------------------

// This software is Copyright (c) 2011 Embarcadero Technologies, Inc. 
// You may only use this software if you are an authorized licensee
// of Delphi, C++Builder or RAD Studio (Embarcadero Products).
// This software is considered a Redistributable as defined under
// the software license agreement that comes with the Embarcadero Products
// and is subject to that software license agreement.

//---------------------------------------------------------------------------
// Do not edit. This file is machine generated by the Resource DLL Wizard.

library richedit;

{ITE} {DFMFileType} {reabout.dfm}
{ITE} {DFMFileType} {remain.dfm}
{ITE} {RCFileType} {richedit_DRC.rc}

{$R 'reabout.dfm' AboutBox:TForm}
{$R 'remain.dfm' MainForm:TForm}
{$R 'richedit_DRC.res' 'richedit_DRC.rc'}

{$E FRA}

begin
end.
